### ISSUE TITLE
Kanban board setting

### ISSUE THREAD

**Issue by Innocent259** [Innocent259/Javascript-capstone#21]
Our GitHub project link: https://github.com/Innocent259/Javascript-capstone
Our team, we are a group of two: @Innocent259 and @yin-ka

**Comment by wayungi** [comment]
Hi @Innocent259 , 

![image](https://user-images.githubusercontent.com/99656687/220082459-c1b049c7-5498-42e7-942b-ec7a05d3e603.png)

Great work, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**Remember: Every finish line 🏁  is the beginning of a new race 🐎** 

## Highlights
- [ ] All Student C tasks have been deleted ✔️ 
- [ ]  All tasks have been assigned to team members ✔️ 
- [ ] All columns are present ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
